language: android
android:
  components:
    - build-tools-19.1.0
    - android-19

script:
  - ant debug

deploy:
  provider: releases
  api-key: "1669e99bd8335639156bd7398c992e0d224d13ea"
  file: "/home/travis/build/textkeu/TravisSample/bin/TravisSample-debug.apk"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true  
  
notifications:
  email: false
  slack: textkeu:7pO2Ny0GaIOAg1NRsKvWPf7K