language: android
android:
  components:
    - build-tools-19.1.0
    - android-19

install:
  # check python version
  - python --version
  #- sudo apt-get install python-pip
  - sudo pip install --upgrade google-api-python-client

script:
  - ant debug

after_success:
  # change directory to bin folder
  - cd /home/travis/build/textkeu/TravisSample/bin/
  # copy python file
  - cp /home/travis/build/textkeu/TravisSample/custom4travis/main.py main.py
  # call python file
  - python sample.py
  
notifications:
  email: false
  slack: textkeu:7pO2Ny0GaIOAg1NRsKvWPf7K
